apiVersion: v1
kind: ConfigMap
metadata:
  name: $k8sAppName-env
  namespace: $k8sNamespace
data:
  ENVVAR1: $branchName
  ENVVAR2: commit_$commitHash
  ENVVAR3: $environment
  SECRET: /app/secrets/credentials
---
apiVersion: batch/v1
kind: Job
metadata:
  name: $k8sAppName
  namespace: $k8sNamespace
spec:
  ttlSecondsAfterFinished: 90
  template:
    metadata:
      labels:
        app: $k8sAppName
    spec:
      containers:
      - name: $k8sAppName
        image: artifactory.teslamotors.com:2194/$dockerShop/$dockerAppName:$IMG_TAG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: creds-vol
          mountPath: /app/secrets
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 200m #update allcoation here based on app size 100-200m is usually good
            memory: 512Mi #update allcoation here based on app size 512Mi is usually good
        envFrom:
        - configMapRef:
            name: $k8sAppName-env
      volumes:
      - name: creds-vol
        secret:
          secretName: $k8sSecretName
      imagePullSecrets:
      - name: gf1pe-docker-registry-creds
      restartPolicy: Never
      activeDeadlineSeconds: 900