name: Docker Build

on:
  push:
    branches-ignore:
      - 'master'
      - 'dev'
jobs:

  Build:

    runs-on: [ self-hosted ]

    env:
      #Static variables for gf1pe-docker-local
      DOCKER_REGISTRY: artifactory.teslamotors.com:2194
      DOCKER_TAG_PROD: latest
      DOCKER_TAG_DEV: dev
      #Set these variables unique for each deployment
      DOCKER_FOLDER: demo-apps
      DOCKER_APPNAME: python-app-template

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to docker registry
      uses: actions/login-action@v1
      with: 
        registry: ${{ env.DOCKER_REGISTRY}}
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Deploy Dev Image
      uses: actions/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        # tags: ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_FOLDER}}/${{ env.DOCKER_APPNAME}}:${{ env.DOCKER_TAG_DEV}}
